---
# Recovering facts
- setup:
  register: facts

# getting date time variable
- set_fact:
    date_time: "{{ facts.ansible_facts.ansible_date_time.iso8601_basic_short }}"

- debug:
    var: date_time
